#!/usr/bin/env ruby
# frozen_string_literal: true

raise 'Please provide a path to a markdown file' if ARGV.empty?

path = ARGV[0]

require 'bundler/inline'
require 'rubygems'

gemfile do
  source 'https://rubygems.org'
  gem 'redcarpet', '~> 3.3', '>= 3.3.4'
end


content = File.read(path)
renderer = Redcarpet::Render::HTML.new
markdown = Redcarpet::Markdown.new(renderer, extensions = {quote: true, fenced_code_blocks: true})

html = markdown.render(content).gsub("&#39;", "'")

puts html
